name: ci-storefront

on:
  push:
    branches: [ master, main ]
    paths:
      - 'storefront/**'
      - '.github/workflows/ci-storefront.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'storefront/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'storefront/package-lock.json'
      - name: Install deps
        run: npm ci
        working-directory: storefront
      - name: Lint
        run: npm run lint
        working-directory: storefront
      - name: Typecheck
        run: npm run typecheck
        working-directory: storefront
      - name: Build
        run: npm run build
        working-directory: storefront

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'storefront/package-lock.json'
      - name: Install deps
        run: npm ci
        working-directory: storefront
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: storefront
      - name: Run E2E tests
        run: npx playwright test
        working-directory: storefront
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: storefront/playwright-report
          if-no-files-found: ignore
          retention-days: 7
      - name: Upload Playwright test results (traces, screenshots, videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: storefront/test-results
          if-no-files-found: ignore
          retention-days: 7
